# temporarily store GitHub traffic data
# from: https://github.com/marketplace/actions/repository-traffic
on:
  schedule: 
    # runs once a week on sunday
    - cron: "55 23 * * 0"

jobs:
  # This workflow contains a single job called "traffic"
  traffic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # DevGoal: figure out how to put the traffic data directly into doc/source/tracking
    - uses: actions/checkout@v2
      with:
        ref: "traffic"
    
    # Calculates traffic and clones and stores in CSV file
    - name: GitHub traffic 
      uses: sangonzal/repository-traffic-action@v0.1.2
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }} 
    
    # Custom steps to move files to another dir and format plot
    - name: Move files
      run: traffic_data_mgmt.py
    
    # Commits files to repository
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Jessica Scheick
        message: "GitHub traffic"
        add: "./doc/source/tracking/traffic/*"
#         add: "./traffic/*"
        ref: "traffic"  # commits to branch "traffic"